version: "3.9"

services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - application-network
    depends_on:
      - application
      - grafana

  application:
    build:
      context: ./AspNetCoreApp
      dockerfile: Dockerfile
    ports:
      - "5037:80"
    networks:
      - application-network
    environment:
      - MongoDB__ConnectionString=mongodb://mongodb:27017/items-db
      - Elasticsearch__Url=http://elasticsearch:9200
    depends_on:
      - mongodb
      - elasticsearch

  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    networks:
      - application-network

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.16.2
    container_name: elasticsearch
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - "discovery.type=single-node"
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
      - application-network

  telegraf:
    image: telegraf:latest
    environment:
      - HOST_PROC=/host/proc
      - HOST_SYS=/host/sys
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - ./telegraf.conf:/etc/telegraf/telegraf.conf:ro
    restart: always
    # "1000" is the group id of the docker daemon, run: $(stat -c '%g' /var/run/docker.sock)
    # see: https://www.influxdata.com/blog/docker-run-telegraf-as-non-root/
    user: telegraf:1000
    networks:
      - application-network
    depends_on:
      - application
      - mongodb
      - elasticsearch
      - influxdb

  influxdb:
    image: influxdb:1.8
    container_name: influxdb
    ports:
      - "8086:8086"
    restart: always
    environment:
      - INFLUXDB_DB=app-metrics-db
      - INFLUXDB_ADMIN_ENABLED=true
      - INFLUXDB_ADMIN_USER=admin
      - INFLUXDB_ADMIN_PASSWORD=yourpassword
    volumes:
      - ./influxdb:/var/lib/influxdb
    networks:
      - application-network

  grafana:
    image: grafana/grafana:latest
    volumes:
      - ./grafana:/var/lib/grafana
    ports:
      - "3000:3000"
    restart: always
    depends_on:
      - influxdb
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin123
      - GF_INSTALL_PLUGINS=grafana-piechart-panel
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_SERVER_ROOT_URL=http://localhost:3000
    networks:
      - application-network

networks:
  application-network:
